# Generated by Django 5.0.4 on 2024-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=1000)),
                ('time', models.TimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=1000)),
            ],
        ),
    ]
